clickhouse:
  enabled: true
  fullnameOverride: o11y-telemetrystore-clickhouse
  image:
    repository: clickhouse/clickhouse-server
    tag: 25.5.6
  layout:
    replicasCount: 0
    shardsCount: 1
  zookeeper:
    enabled: true
    fullnameOverride: o11y-telemetrykeeper-zookeeper
    image:
      repository: o11y/zookeeper
      tag: 3.7.1
    replicaCount: 1
fullnameOverride: o11y
otelCollector:
  enabled: true
  env:
    O11Y_OTEL_COLLECTOR_TIMEOUT: 10m
  image:
    repository: signoz/signoz-otel-collector
    tag: latest
  name: ingester
  ports:
    otlp:
      containerPort: 4317
      enabled: true
      protocol: TCP
      servicePort: 4317
    otlp-http:
      containerPort: 4318
      enabled: true
      protocol: TCP
      servicePort: 4318
  replicaCount: 1
postgresql:
  auth:
    database: o11y
    password: o11y
    username: o11y
  enabled: true
  fullnameOverride: o11y-metastore-postgres
  image:
    repository: postgres
    tag: 16
o11y:
  env:
    O11Y_SQLSTORE_POSTGRES_DSN: postgres://o11y:o11y@o11y-metastore-postgres:5432/o11y?sslmode=disable
    O11Y_SQLSTORE_PROVIDER: postgres
    O11Y_TELEMETRYSTORE_CLICKHOUSE_DSN: tcp://o11y-telemetrystore-clickhouse:9000
    O11Y_TELEMETRYSTORE_PROVIDER: clickhouse
  image:
    repository: signoz/signoz
    tag: latest
  name: o11y
  replicaCount: 1
  service:
    internalPort: 8085
    opampPort: 4320
    port: 8080
    type: ClusterIP
telemetryStoreMigrator:
  enabled: true
  env:
    O11Y_OTEL_COLLECTOR_TIMEOUT: 10m
  name: o11y-telemetrystore-migrator
