import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DOCUMENT, loadDocument, type KeyType } from './openapi-doc';
import { text } from './mdx';

// THE KEY TYPES, generated from THE document.
//
// /docs/api-keys is the first page a reader needs and the one that was most
// wrong: it documented three key types, cloud mints two, and neither of the
// other two has ever existed. It went wrong the ordinary way — someone typed
// what a key looked like, and nothing afterwards ever compared the two.
//
// So the table is not typed. `/v1/keys` is the key resource, its Go source names
// each class beside its prefix, zipdoc lifts those comments into the document,
// and openapi-doc reads them back as Document.keys. This renders that. The prose
// around it on the page stays authored, because how to keep a credential out of
// a git history is not something the API describes — but every prefix, every
// class name and every "what it resolves to" comes from the handler.
//
// It is included rather than routed: `<include>` splices this into api-keys.mdx
// at compile time, so the fact appears in the page and this file is not a page.
// It lives outside content/ because source.config globs `**/*.mdx` there and
// would give a fragment its own URL.

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const APP_ROOT = path.resolve(SCRIPT_DIR, '..');
export const KEY_TYPES_FRAGMENT = path.join(APP_ROOT, 'generated/key-types.mdx');

/**
 * The one-line reading of a class, for the table's last column.
 *
 * The document states each class as `"secret" (sk-, session-equivalent, belongs
 * on a server)`, and that parenthetical is the sentence worth publishing — it is
 * the handler's own summary of what the class is FOR. Where a class carries no
 * note, the class name stands alone rather than inventing one.
 */
const reading = (k: KeyType): string => (k.note ? text(k.note) : `The ${k.name} key.`);

export function genKeyTypes(): KeyType[] {
  const doc = loadDocument(DOCUMENT);

  const rows = doc.keys
    .map((k) => `| \`${k.prefix}\` | ${text(k.name)} | ${reading(k)} |`)
    .join('\n');

  const browser = doc.keys.find((k) => k.publishable)!;
  const server = doc.keys.filter((k) => !k.publishable);

  const body = `{/* Generated by scripts/gen-key-types.ts from hanzoai/cloud's openapi.yaml.
    Every value below is the /v1/keys handler's own doc comment. Do not edit. */}

| Prefix | Type | What it is |
|--------|------|------------|
${rows}

${
  server.length === 1
    ? `\`${server[0].prefix}\` belongs on a server and \`${browser.prefix}\` may ship in a browser bundle.`
    : `\`${browser.prefix}\` may ship in a browser bundle; every other type belongs on a server.`
} A key spelled any other way is refused at the door — never guessed at, never
defaulted to the safer-sounding one.
`;

  fs.mkdirSync(path.dirname(KEY_TYPES_FRAGMENT), { recursive: true });
  fs.writeFileSync(KEY_TYPES_FRAGMENT, body);
  console.log(
    `[keys] ${doc.keys.map((k) => `${k.name} ${k.prefix}`).join(', ')} -> ` +
      path.relative(APP_ROOT, KEY_TYPES_FRAGMENT),
  );
  return doc.keys;
}

if (import.meta.main) genKeyTypes();
