apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: o11y-telemetrystore-clickhouse-operator
    app.kubernetes.io/name: o11y-telemetrystore-clickhouse-operator
    app.kubernetes.io/version: 0.25.3
  name: o11y-telemetrystore-clickhouse-operator
