apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: ingester
    app.kubernetes.io/instance: o11y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o11y-ingester
  name: o11y-ingester
