// @ts-nocheck
import { browser } from '@hanzo/docs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("@hanzo/docs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"datasets.mdx": () => import("../content/docs/datasets.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "models.mdx": () => import("../content/docs/models.mdx?collection=docs"), "training.mdx": () => import("../content/docs/training.mdx?collection=docs"), "api/chat-completions.mdx": () => import("../content/docs/api/chat-completions.mdx?collection=docs"), "api/embeddings.mdx": () => import("../content/docs/api/embeddings.mdx?collection=docs"), "api/index.mdx": () => import("../content/docs/api/index.mdx?collection=docs"), "api/models.mdx": () => import("../content/docs/api/models.mdx?collection=docs"), "api/pricing.mdx": () => import("../content/docs/api/pricing.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/quickstart.mdx": () => import("../content/docs/getting-started/quickstart.mdx?collection=docs"), "models/zen3-embedding.mdx": () => import("../content/docs/models/zen3-embedding.mdx?collection=docs"), "models/zen3-guard.mdx": () => import("../content/docs/models/zen3-guard.mdx?collection=docs"), "models/zen3-nano.mdx": () => import("../content/docs/models/zen3-nano.mdx?collection=docs"), "models/zen3-omni.mdx": () => import("../content/docs/models/zen3-omni.mdx?collection=docs"), "models/zen3-vl.mdx": () => import("../content/docs/models/zen3-vl.mdx?collection=docs"), "models/zen4-coder-flash.mdx": () => import("../content/docs/models/zen4-coder-flash.mdx?collection=docs"), "models/zen4-coder-pro.mdx": () => import("../content/docs/models/zen4-coder-pro.mdx?collection=docs"), "models/zen4-coder.mdx": () => import("../content/docs/models/zen4-coder.mdx?collection=docs"), "models/zen4-max.mdx": () => import("../content/docs/models/zen4-max.mdx?collection=docs"), "models/zen4-mini.mdx": () => import("../content/docs/models/zen4-mini.mdx?collection=docs"), "models/zen4-pro.mdx": () => import("../content/docs/models/zen4-pro.mdx?collection=docs"), "models/zen4-thinking.mdx": () => import("../content/docs/models/zen4-thinking.mdx?collection=docs"), "models/zen4-ultra.mdx": () => import("../content/docs/models/zen4-ultra.mdx?collection=docs"), "models/zen4.mdx": () => import("../content/docs/models/zen4.mdx?collection=docs"), "training/cloud.mdx": () => import("../content/docs/training/cloud.mdx?collection=docs"), "training/cuda.mdx": () => import("../content/docs/training/cuda.mdx?collection=docs"), "training/mlx.mdx": () => import("../content/docs/training/mlx.mdx?collection=docs"), "training/overview.mdx": () => import("../content/docs/training/overview.mdx?collection=docs"), }),
};
export default browserCollections;