// @ts-nocheck
import { default as __fd_glob_59 } from "../content/docs/meta.json?collection=docs"
import * as __fd_glob_58 from "../content/docs/models/zen4.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/models/zen4-ultra.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/models/zen4-thinking.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/models/zen4-pro.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/models/zen4-mini.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/models/zen4-max.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/models/zen4-coder.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/models/zen4-coder-pro.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/models/zen4-coder-flash.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/models/zen3-vl.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/models/zen3-omni.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/models/zen3-nano.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/models/zen3-guard.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/models/zen3-embedding.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/models/zen.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/models/zen-world.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/models/zen-voyager.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/models/zen-vl.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/models/zen-video.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/models/zen-video-i2v.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/models/zen-translator.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/models/zen-scribe.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/models/zen-reranker.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/models/zen-pro.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/models/zen-omni.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/models/zen-nano.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/models/zen-musician.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/models/zen-max.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/models/zen-live.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/models/zen-guard-stream.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/models/zen-guard-gen.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/models/zen-foley.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/models/zen-eco.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/models/zen-dub.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/models/zen-dub-live.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/models/zen-director.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/models/zen-designer.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/models/zen-coder.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/models/zen-coder-flash.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/models/zen-code.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/models/zen-artist.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/models/zen-artist-edit.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/models/zen-agent.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/models/zen-3d.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/training/overview.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/training/mlx.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/training/cuda.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/training/cloud.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/getting-started/quickstart.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/api/pricing.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/api/models.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/api/index.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/api/embeddings.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/api/chat-completions.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/training.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/models.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/datasets.mdx?collection=docs"
import { server } from '@hanzo/docs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("@hanzo/docs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_59, }, {"datasets.mdx": __fd_glob_0, "index.mdx": __fd_glob_1, "models.mdx": __fd_glob_2, "training.mdx": __fd_glob_3, "api/chat-completions.mdx": __fd_glob_4, "api/embeddings.mdx": __fd_glob_5, "api/index.mdx": __fd_glob_6, "api/models.mdx": __fd_glob_7, "api/pricing.mdx": __fd_glob_8, "getting-started/installation.mdx": __fd_glob_9, "getting-started/quickstart.mdx": __fd_glob_10, "training/cloud.mdx": __fd_glob_11, "training/cuda.mdx": __fd_glob_12, "training/mlx.mdx": __fd_glob_13, "training/overview.mdx": __fd_glob_14, "models/zen-3d.mdx": __fd_glob_15, "models/zen-agent.mdx": __fd_glob_16, "models/zen-artist-edit.mdx": __fd_glob_17, "models/zen-artist.mdx": __fd_glob_18, "models/zen-code.mdx": __fd_glob_19, "models/zen-coder-flash.mdx": __fd_glob_20, "models/zen-coder.mdx": __fd_glob_21, "models/zen-designer.mdx": __fd_glob_22, "models/zen-director.mdx": __fd_glob_23, "models/zen-dub-live.mdx": __fd_glob_24, "models/zen-dub.mdx": __fd_glob_25, "models/zen-eco.mdx": __fd_glob_26, "models/zen-foley.mdx": __fd_glob_27, "models/zen-guard-gen.mdx": __fd_glob_28, "models/zen-guard-stream.mdx": __fd_glob_29, "models/zen-live.mdx": __fd_glob_30, "models/zen-max.mdx": __fd_glob_31, "models/zen-musician.mdx": __fd_glob_32, "models/zen-nano.mdx": __fd_glob_33, "models/zen-omni.mdx": __fd_glob_34, "models/zen-pro.mdx": __fd_glob_35, "models/zen-reranker.mdx": __fd_glob_36, "models/zen-scribe.mdx": __fd_glob_37, "models/zen-translator.mdx": __fd_glob_38, "models/zen-video-i2v.mdx": __fd_glob_39, "models/zen-video.mdx": __fd_glob_40, "models/zen-vl.mdx": __fd_glob_41, "models/zen-voyager.mdx": __fd_glob_42, "models/zen-world.mdx": __fd_glob_43, "models/zen.mdx": __fd_glob_44, "models/zen3-embedding.mdx": __fd_glob_45, "models/zen3-guard.mdx": __fd_glob_46, "models/zen3-nano.mdx": __fd_glob_47, "models/zen3-omni.mdx": __fd_glob_48, "models/zen3-vl.mdx": __fd_glob_49, "models/zen4-coder-flash.mdx": __fd_glob_50, "models/zen4-coder-pro.mdx": __fd_glob_51, "models/zen4-coder.mdx": __fd_glob_52, "models/zen4-max.mdx": __fd_glob_53, "models/zen4-mini.mdx": __fd_glob_54, "models/zen4-pro.mdx": __fd_glob_55, "models/zen4-thinking.mdx": __fd_glob_56, "models/zen4-ultra.mdx": __fd_glob_57, "models/zen4.mdx": __fd_glob_58, });