// @ts-nocheck
import * as __fd_glob_124 from "../content/docs/models/zen5.mdx?collection=docs"
import * as __fd_glob_123 from "../content/docs/models/zen5-ultra.mdx?collection=docs"
import * as __fd_glob_122 from "../content/docs/models/zen5-pro.mdx?collection=docs"
import * as __fd_glob_121 from "../content/docs/models/zen5-mini.mdx?collection=docs"
import * as __fd_glob_120 from "../content/docs/models/zen5-max.mdx?collection=docs"
import * as __fd_glob_119 from "../content/docs/models/zen5-coder.mdx?collection=docs"
import * as __fd_glob_118 from "../content/docs/models/zen4.mdx?collection=docs"
import * as __fd_glob_117 from "../content/docs/models/zen4.1.mdx?collection=docs"
import * as __fd_glob_116 from "../content/docs/models/zen4-ultra.mdx?collection=docs"
import * as __fd_glob_115 from "../content/docs/models/zen4-thinking.mdx?collection=docs"
import * as __fd_glob_114 from "../content/docs/models/zen4-pro.mdx?collection=docs"
import * as __fd_glob_113 from "../content/docs/models/zen4-mini.mdx?collection=docs"
import * as __fd_glob_112 from "../content/docs/models/zen4-max.mdx?collection=docs"
import * as __fd_glob_111 from "../content/docs/models/zen4-coder.mdx?collection=docs"
import * as __fd_glob_110 from "../content/docs/models/zen4-coder-pro.mdx?collection=docs"
import * as __fd_glob_109 from "../content/docs/models/zen4-coder-flash.mdx?collection=docs"
import * as __fd_glob_108 from "../content/docs/models/zen3-vl.mdx?collection=docs"
import * as __fd_glob_107 from "../content/docs/models/zen3-tts.mdx?collection=docs"
import * as __fd_glob_106 from "../content/docs/models/zen3-tts-hd.mdx?collection=docs"
import * as __fd_glob_105 from "../content/docs/models/zen3-tts-fast.mdx?collection=docs"
import * as __fd_glob_104 from "../content/docs/models/zen3-reranker.mdx?collection=docs"
import * as __fd_glob_103 from "../content/docs/models/zen3-reranker-small.mdx?collection=docs"
import * as __fd_glob_102 from "../content/docs/models/zen3-reranker-medium.mdx?collection=docs"
import * as __fd_glob_101 from "../content/docs/models/zen3-omni.mdx?collection=docs"
import * as __fd_glob_100 from "../content/docs/models/zen3-nano.mdx?collection=docs"
import * as __fd_glob_99 from "../content/docs/models/zen3-image.mdx?collection=docs"
import * as __fd_glob_98 from "../content/docs/models/zen3-image-ssd.mdx?collection=docs"
import * as __fd_glob_97 from "../content/docs/models/zen3-image-sdxl.mdx?collection=docs"
import * as __fd_glob_96 from "../content/docs/models/zen3-image-playground.mdx?collection=docs"
import * as __fd_glob_95 from "../content/docs/models/zen3-image-max.mdx?collection=docs"
import * as __fd_glob_94 from "../content/docs/models/zen3-image-jp.mdx?collection=docs"
import * as __fd_glob_93 from "../content/docs/models/zen3-image-fast.mdx?collection=docs"
import * as __fd_glob_92 from "../content/docs/models/zen3-image-dev.mdx?collection=docs"
import * as __fd_glob_91 from "../content/docs/models/zen3-guard.mdx?collection=docs"
import * as __fd_glob_90 from "../content/docs/models/zen3-embedding.mdx?collection=docs"
import * as __fd_glob_89 from "../content/docs/models/zen3-embedding-small.mdx?collection=docs"
import * as __fd_glob_88 from "../content/docs/models/zen3-embedding-medium.mdx?collection=docs"
import * as __fd_glob_87 from "../content/docs/models/zen3-audio.mdx?collection=docs"
import * as __fd_glob_86 from "../content/docs/models/zen3-audio-fast.mdx?collection=docs"
import * as __fd_glob_85 from "../content/docs/models/zen3-asr.mdx?collection=docs"
import * as __fd_glob_84 from "../content/docs/models/zen3-asr-v1.mdx?collection=docs"
import * as __fd_glob_83 from "../content/docs/models/zen.mdx?collection=docs"
import * as __fd_glob_82 from "../content/docs/models/zen-world.mdx?collection=docs"
import * as __fd_glob_81 from "../content/docs/models/zen-voyager.mdx?collection=docs"
import * as __fd_glob_80 from "../content/docs/models/zen-vl.mdx?collection=docs"
import * as __fd_glob_79 from "../content/docs/models/zen-video.mdx?collection=docs"
import * as __fd_glob_78 from "../content/docs/models/zen-video-i2v.mdx?collection=docs"
import * as __fd_glob_77 from "../content/docs/models/zen-translator.mdx?collection=docs"
import * as __fd_glob_76 from "../content/docs/models/zen-scribe.mdx?collection=docs"
import * as __fd_glob_75 from "../content/docs/models/zen-reranker.mdx?collection=docs"
import * as __fd_glob_74 from "../content/docs/models/zen-pro.mdx?collection=docs"
import * as __fd_glob_73 from "../content/docs/models/zen-omni.mdx?collection=docs"
import * as __fd_glob_72 from "../content/docs/models/zen-next.mdx?collection=docs"
import * as __fd_glob_71 from "../content/docs/models/zen-nano.mdx?collection=docs"
import * as __fd_glob_70 from "../content/docs/models/zen-musician.mdx?collection=docs"
import * as __fd_glob_69 from "../content/docs/models/zen-max.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/models/zen-live.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/models/zen-guard.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/models/zen-guard-stream.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/models/zen-guard-gen.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/models/zen-foley.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/models/zen-embedding.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/models/zen-eco.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/models/zen-dub.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/models/zen-dub-live.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/models/zen-director.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/models/zen-designer.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/models/zen-coder.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/models/zen-coder-flash.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/models/zen-code.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/models/zen-artist.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/models/zen-artist-edit.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/models/zen-agent.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/models/zen-3d.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/training/overview.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/training/mlx.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/training/cuda.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/training/cloud.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/getting-started/quickstart.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/api/pricing.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/api/models.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/api/index.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/api/embeddings.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/api/chat-completions.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/training.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/models.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/datasets.mdx?collection=docs"
import { default as __fd_glob_35 } from "../content/docs/meta.json?collection=docs"
import { frontmatter as __fd_glob_34 } from "../content/blog/zoo-foundation-launch.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_33 } from "../content/blog/zips-governance.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_32 } from "../content/blog/zen5-release.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_31 } from "../content/blog/zen4-ultra.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_30 } from "../content/blog/zen-reranker.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_29 } from "../content/blog/zen-mode-architecture.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_28 } from "../content/blog/zen-lm-launch.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_27 } from "../content/blog/zen-collaboration.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_26 } from "../content/blog/zen-3.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_25 } from "../content/blog/training-llms-collective-intelligence.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_24 } from "../content/blog/training-gym.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_23 } from "../content/blog/proof-of-ai.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_22 } from "../content/blog/open-weights-philosophy.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_21 } from "../content/blog/open-training-hanzo-network.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_20 } from "../content/blog/ofasys.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_19 } from "../content/blog/ofa.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_18 } from "../content/blog/introducing-zen.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_17 } from "../content/blog/gt-qlora-moe-abliteration.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_16 } from "../content/blog/grpo.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_15 } from "../content/blog/grpo-group-relative-policy-optimization.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_14 } from "../content/blog/global-load-balance.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_13 } from "../content/blog/future-of-open-ai.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_12 } from "../content/blog/federated-learning.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_11 } from "../content/blog/federated-learning-without-compromise.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_10 } from "../content/blog/experience-ledgers.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_9 } from "../content/blog/embedding-spaces-7680-dimensions.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_8 } from "../content/blog/drop-upcycling-zen-mode.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_7 } from "../content/blog/decentralized-compute.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_6 } from "../content/blog/continual-learning-sure-opcm.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_5 } from "../content/blog/chinese-clip.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_4 } from "../content/blog/case-for-desci.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_3 } from "../content/blog/case-for-decentralized-science.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_2 } from "../content/blog/bitdelta-behavioral-compression.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_1 } from "../content/blog/agent-nfts.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_0 } from "../content/blog/7680-dim-embeddings.mdx?collection=blog&only=frontmatter"
import { server } from '@hanzo/docs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("@hanzo/docs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const blog = await create.docLazy("blog", "content/blog", {"7680-dim-embeddings.mdx": __fd_glob_0, "agent-nfts.mdx": __fd_glob_1, "bitdelta-behavioral-compression.mdx": __fd_glob_2, "case-for-decentralized-science.mdx": __fd_glob_3, "case-for-desci.mdx": __fd_glob_4, "chinese-clip.mdx": __fd_glob_5, "continual-learning-sure-opcm.mdx": __fd_glob_6, "decentralized-compute.mdx": __fd_glob_7, "drop-upcycling-zen-mode.mdx": __fd_glob_8, "embedding-spaces-7680-dimensions.mdx": __fd_glob_9, "experience-ledgers.mdx": __fd_glob_10, "federated-learning-without-compromise.mdx": __fd_glob_11, "federated-learning.mdx": __fd_glob_12, "future-of-open-ai.mdx": __fd_glob_13, "global-load-balance.mdx": __fd_glob_14, "grpo-group-relative-policy-optimization.mdx": __fd_glob_15, "grpo.mdx": __fd_glob_16, "gt-qlora-moe-abliteration.mdx": __fd_glob_17, "introducing-zen.mdx": __fd_glob_18, "ofa.mdx": __fd_glob_19, "ofasys.mdx": __fd_glob_20, "open-training-hanzo-network.mdx": __fd_glob_21, "open-weights-philosophy.mdx": __fd_glob_22, "proof-of-ai.mdx": __fd_glob_23, "training-gym.mdx": __fd_glob_24, "training-llms-collective-intelligence.mdx": __fd_glob_25, "zen-3.mdx": __fd_glob_26, "zen-collaboration.mdx": __fd_glob_27, "zen-lm-launch.mdx": __fd_glob_28, "zen-mode-architecture.mdx": __fd_glob_29, "zen-reranker.mdx": __fd_glob_30, "zen4-ultra.mdx": __fd_glob_31, "zen5-release.mdx": __fd_glob_32, "zips-governance.mdx": __fd_glob_33, "zoo-foundation-launch.mdx": __fd_glob_34, }, {"7680-dim-embeddings.mdx": () => import("../content/blog/7680-dim-embeddings.mdx?collection=blog"), "agent-nfts.mdx": () => import("../content/blog/agent-nfts.mdx?collection=blog"), "bitdelta-behavioral-compression.mdx": () => import("../content/blog/bitdelta-behavioral-compression.mdx?collection=blog"), "case-for-decentralized-science.mdx": () => import("../content/blog/case-for-decentralized-science.mdx?collection=blog"), "case-for-desci.mdx": () => import("../content/blog/case-for-desci.mdx?collection=blog"), "chinese-clip.mdx": () => import("../content/blog/chinese-clip.mdx?collection=blog"), "continual-learning-sure-opcm.mdx": () => import("../content/blog/continual-learning-sure-opcm.mdx?collection=blog"), "decentralized-compute.mdx": () => import("../content/blog/decentralized-compute.mdx?collection=blog"), "drop-upcycling-zen-mode.mdx": () => import("../content/blog/drop-upcycling-zen-mode.mdx?collection=blog"), "embedding-spaces-7680-dimensions.mdx": () => import("../content/blog/embedding-spaces-7680-dimensions.mdx?collection=blog"), "experience-ledgers.mdx": () => import("../content/blog/experience-ledgers.mdx?collection=blog"), "federated-learning-without-compromise.mdx": () => import("../content/blog/federated-learning-without-compromise.mdx?collection=blog"), "federated-learning.mdx": () => import("../content/blog/federated-learning.mdx?collection=blog"), "future-of-open-ai.mdx": () => import("../content/blog/future-of-open-ai.mdx?collection=blog"), "global-load-balance.mdx": () => import("../content/blog/global-load-balance.mdx?collection=blog"), "grpo-group-relative-policy-optimization.mdx": () => import("../content/blog/grpo-group-relative-policy-optimization.mdx?collection=blog"), "grpo.mdx": () => import("../content/blog/grpo.mdx?collection=blog"), "gt-qlora-moe-abliteration.mdx": () => import("../content/blog/gt-qlora-moe-abliteration.mdx?collection=blog"), "introducing-zen.mdx": () => import("../content/blog/introducing-zen.mdx?collection=blog"), "ofa.mdx": () => import("../content/blog/ofa.mdx?collection=blog"), "ofasys.mdx": () => import("../content/blog/ofasys.mdx?collection=blog"), "open-training-hanzo-network.mdx": () => import("../content/blog/open-training-hanzo-network.mdx?collection=blog"), "open-weights-philosophy.mdx": () => import("../content/blog/open-weights-philosophy.mdx?collection=blog"), "proof-of-ai.mdx": () => import("../content/blog/proof-of-ai.mdx?collection=blog"), "training-gym.mdx": () => import("../content/blog/training-gym.mdx?collection=blog"), "training-llms-collective-intelligence.mdx": () => import("../content/blog/training-llms-collective-intelligence.mdx?collection=blog"), "zen-3.mdx": () => import("../content/blog/zen-3.mdx?collection=blog"), "zen-collaboration.mdx": () => import("../content/blog/zen-collaboration.mdx?collection=blog"), "zen-lm-launch.mdx": () => import("../content/blog/zen-lm-launch.mdx?collection=blog"), "zen-mode-architecture.mdx": () => import("../content/blog/zen-mode-architecture.mdx?collection=blog"), "zen-reranker.mdx": () => import("../content/blog/zen-reranker.mdx?collection=blog"), "zen4-ultra.mdx": () => import("../content/blog/zen4-ultra.mdx?collection=blog"), "zen5-release.mdx": () => import("../content/blog/zen5-release.mdx?collection=blog"), "zips-governance.mdx": () => import("../content/blog/zips-governance.mdx?collection=blog"), "zoo-foundation-launch.mdx": () => import("../content/blog/zoo-foundation-launch.mdx?collection=blog"), });

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_35, }, {"datasets.mdx": __fd_glob_36, "index.mdx": __fd_glob_37, "models.mdx": __fd_glob_38, "training.mdx": __fd_glob_39, "api/chat-completions.mdx": __fd_glob_40, "api/embeddings.mdx": __fd_glob_41, "api/index.mdx": __fd_glob_42, "api/models.mdx": __fd_glob_43, "api/pricing.mdx": __fd_glob_44, "getting-started/installation.mdx": __fd_glob_45, "getting-started/quickstart.mdx": __fd_glob_46, "training/cloud.mdx": __fd_glob_47, "training/cuda.mdx": __fd_glob_48, "training/mlx.mdx": __fd_glob_49, "training/overview.mdx": __fd_glob_50, "models/zen-3d.mdx": __fd_glob_51, "models/zen-agent.mdx": __fd_glob_52, "models/zen-artist-edit.mdx": __fd_glob_53, "models/zen-artist.mdx": __fd_glob_54, "models/zen-code.mdx": __fd_glob_55, "models/zen-coder-flash.mdx": __fd_glob_56, "models/zen-coder.mdx": __fd_glob_57, "models/zen-designer.mdx": __fd_glob_58, "models/zen-director.mdx": __fd_glob_59, "models/zen-dub-live.mdx": __fd_glob_60, "models/zen-dub.mdx": __fd_glob_61, "models/zen-eco.mdx": __fd_glob_62, "models/zen-embedding.mdx": __fd_glob_63, "models/zen-foley.mdx": __fd_glob_64, "models/zen-guard-gen.mdx": __fd_glob_65, "models/zen-guard-stream.mdx": __fd_glob_66, "models/zen-guard.mdx": __fd_glob_67, "models/zen-live.mdx": __fd_glob_68, "models/zen-max.mdx": __fd_glob_69, "models/zen-musician.mdx": __fd_glob_70, "models/zen-nano.mdx": __fd_glob_71, "models/zen-next.mdx": __fd_glob_72, "models/zen-omni.mdx": __fd_glob_73, "models/zen-pro.mdx": __fd_glob_74, "models/zen-reranker.mdx": __fd_glob_75, "models/zen-scribe.mdx": __fd_glob_76, "models/zen-translator.mdx": __fd_glob_77, "models/zen-video-i2v.mdx": __fd_glob_78, "models/zen-video.mdx": __fd_glob_79, "models/zen-vl.mdx": __fd_glob_80, "models/zen-voyager.mdx": __fd_glob_81, "models/zen-world.mdx": __fd_glob_82, "models/zen.mdx": __fd_glob_83, "models/zen3-asr-v1.mdx": __fd_glob_84, "models/zen3-asr.mdx": __fd_glob_85, "models/zen3-audio-fast.mdx": __fd_glob_86, "models/zen3-audio.mdx": __fd_glob_87, "models/zen3-embedding-medium.mdx": __fd_glob_88, "models/zen3-embedding-small.mdx": __fd_glob_89, "models/zen3-embedding.mdx": __fd_glob_90, "models/zen3-guard.mdx": __fd_glob_91, "models/zen3-image-dev.mdx": __fd_glob_92, "models/zen3-image-fast.mdx": __fd_glob_93, "models/zen3-image-jp.mdx": __fd_glob_94, "models/zen3-image-max.mdx": __fd_glob_95, "models/zen3-image-playground.mdx": __fd_glob_96, "models/zen3-image-sdxl.mdx": __fd_glob_97, "models/zen3-image-ssd.mdx": __fd_glob_98, "models/zen3-image.mdx": __fd_glob_99, "models/zen3-nano.mdx": __fd_glob_100, "models/zen3-omni.mdx": __fd_glob_101, "models/zen3-reranker-medium.mdx": __fd_glob_102, "models/zen3-reranker-small.mdx": __fd_glob_103, "models/zen3-reranker.mdx": __fd_glob_104, "models/zen3-tts-fast.mdx": __fd_glob_105, "models/zen3-tts-hd.mdx": __fd_glob_106, "models/zen3-tts.mdx": __fd_glob_107, "models/zen3-vl.mdx": __fd_glob_108, "models/zen4-coder-flash.mdx": __fd_glob_109, "models/zen4-coder-pro.mdx": __fd_glob_110, "models/zen4-coder.mdx": __fd_glob_111, "models/zen4-max.mdx": __fd_glob_112, "models/zen4-mini.mdx": __fd_glob_113, "models/zen4-pro.mdx": __fd_glob_114, "models/zen4-thinking.mdx": __fd_glob_115, "models/zen4-ultra.mdx": __fd_glob_116, "models/zen4.1.mdx": __fd_glob_117, "models/zen4.mdx": __fd_glob_118, "models/zen5-coder.mdx": __fd_glob_119, "models/zen5-max.mdx": __fd_glob_120, "models/zen5-mini.mdx": __fd_glob_121, "models/zen5-pro.mdx": __fd_glob_122, "models/zen5-ultra.mdx": __fd_glob_123, "models/zen5.mdx": __fd_glob_124, });