// @ts-nocheck
import * as __fd_glob_162 from "../content/docs/models/zen5.mdx?collection=docs"
import * as __fd_glob_161 from "../content/docs/models/zen5-ultra.mdx?collection=docs"
import * as __fd_glob_160 from "../content/docs/models/zen5-pro.mdx?collection=docs"
import * as __fd_glob_159 from "../content/docs/models/zen5-mini.mdx?collection=docs"
import * as __fd_glob_158 from "../content/docs/models/zen5-max.mdx?collection=docs"
import * as __fd_glob_157 from "../content/docs/models/zen5-coder.mdx?collection=docs"
import * as __fd_glob_156 from "../content/docs/models/zen4.mdx?collection=docs"
import * as __fd_glob_155 from "../content/docs/models/zen4.1.mdx?collection=docs"
import * as __fd_glob_154 from "../content/docs/models/zen4-ultra.mdx?collection=docs"
import * as __fd_glob_153 from "../content/docs/models/zen4-thinking.mdx?collection=docs"
import * as __fd_glob_152 from "../content/docs/models/zen4-pro.mdx?collection=docs"
import * as __fd_glob_151 from "../content/docs/models/zen4-mini.mdx?collection=docs"
import * as __fd_glob_150 from "../content/docs/models/zen4-max.mdx?collection=docs"
import * as __fd_glob_149 from "../content/docs/models/zen4-coder.mdx?collection=docs"
import * as __fd_glob_148 from "../content/docs/models/zen4-coder-pro.mdx?collection=docs"
import * as __fd_glob_147 from "../content/docs/models/zen4-coder-flash.mdx?collection=docs"
import * as __fd_glob_146 from "../content/docs/models/zen3-vl.mdx?collection=docs"
import * as __fd_glob_145 from "../content/docs/models/zen3-tts.mdx?collection=docs"
import * as __fd_glob_144 from "../content/docs/models/zen3-tts-hd.mdx?collection=docs"
import * as __fd_glob_143 from "../content/docs/models/zen3-tts-fast.mdx?collection=docs"
import * as __fd_glob_142 from "../content/docs/models/zen3-reranker.mdx?collection=docs"
import * as __fd_glob_141 from "../content/docs/models/zen3-reranker-small.mdx?collection=docs"
import * as __fd_glob_140 from "../content/docs/models/zen3-reranker-medium.mdx?collection=docs"
import * as __fd_glob_139 from "../content/docs/models/zen3-omni.mdx?collection=docs"
import * as __fd_glob_138 from "../content/docs/models/zen3-nano.mdx?collection=docs"
import * as __fd_glob_137 from "../content/docs/models/zen3-image.mdx?collection=docs"
import * as __fd_glob_136 from "../content/docs/models/zen3-image-ssd.mdx?collection=docs"
import * as __fd_glob_135 from "../content/docs/models/zen3-image-sdxl.mdx?collection=docs"
import * as __fd_glob_134 from "../content/docs/models/zen3-image-playground.mdx?collection=docs"
import * as __fd_glob_133 from "../content/docs/models/zen3-image-max.mdx?collection=docs"
import * as __fd_glob_132 from "../content/docs/models/zen3-image-jp.mdx?collection=docs"
import * as __fd_glob_131 from "../content/docs/models/zen3-image-fast.mdx?collection=docs"
import * as __fd_glob_130 from "../content/docs/models/zen3-image-dev.mdx?collection=docs"
import * as __fd_glob_129 from "../content/docs/models/zen3-guard.mdx?collection=docs"
import * as __fd_glob_128 from "../content/docs/models/zen3-embedding.mdx?collection=docs"
import * as __fd_glob_127 from "../content/docs/models/zen3-embedding-small.mdx?collection=docs"
import * as __fd_glob_126 from "../content/docs/models/zen3-embedding-medium.mdx?collection=docs"
import * as __fd_glob_125 from "../content/docs/models/zen3-audio.mdx?collection=docs"
import * as __fd_glob_124 from "../content/docs/models/zen3-audio-fast.mdx?collection=docs"
import * as __fd_glob_123 from "../content/docs/models/zen3-asr.mdx?collection=docs"
import * as __fd_glob_122 from "../content/docs/models/zen3-asr-v1.mdx?collection=docs"
import * as __fd_glob_121 from "../content/docs/models/zen.mdx?collection=docs"
import * as __fd_glob_120 from "../content/docs/models/zen-world.mdx?collection=docs"
import * as __fd_glob_119 from "../content/docs/models/zen-voyager.mdx?collection=docs"
import * as __fd_glob_118 from "../content/docs/models/zen-vl.mdx?collection=docs"
import * as __fd_glob_117 from "../content/docs/models/zen-video.mdx?collection=docs"
import * as __fd_glob_116 from "../content/docs/models/zen-video-i2v.mdx?collection=docs"
import * as __fd_glob_115 from "../content/docs/models/zen-translator.mdx?collection=docs"
import * as __fd_glob_114 from "../content/docs/models/zen-scribe.mdx?collection=docs"
import * as __fd_glob_113 from "../content/docs/models/zen-reranker.mdx?collection=docs"
import * as __fd_glob_112 from "../content/docs/models/zen-pro.mdx?collection=docs"
import * as __fd_glob_111 from "../content/docs/models/zen-omni.mdx?collection=docs"
import * as __fd_glob_110 from "../content/docs/models/zen-next.mdx?collection=docs"
import * as __fd_glob_109 from "../content/docs/models/zen-nano.mdx?collection=docs"
import * as __fd_glob_108 from "../content/docs/models/zen-musician.mdx?collection=docs"
import * as __fd_glob_107 from "../content/docs/models/zen-max.mdx?collection=docs"
import * as __fd_glob_106 from "../content/docs/models/zen-live.mdx?collection=docs"
import * as __fd_glob_105 from "../content/docs/models/zen-guard.mdx?collection=docs"
import * as __fd_glob_104 from "../content/docs/models/zen-guard-stream.mdx?collection=docs"
import * as __fd_glob_103 from "../content/docs/models/zen-guard-gen.mdx?collection=docs"
import * as __fd_glob_102 from "../content/docs/models/zen-foley.mdx?collection=docs"
import * as __fd_glob_101 from "../content/docs/models/zen-embedding.mdx?collection=docs"
import * as __fd_glob_100 from "../content/docs/models/zen-eco.mdx?collection=docs"
import * as __fd_glob_99 from "../content/docs/models/zen-dub.mdx?collection=docs"
import * as __fd_glob_98 from "../content/docs/models/zen-dub-live.mdx?collection=docs"
import * as __fd_glob_97 from "../content/docs/models/zen-director.mdx?collection=docs"
import * as __fd_glob_96 from "../content/docs/models/zen-designer.mdx?collection=docs"
import * as __fd_glob_95 from "../content/docs/models/zen-coder.mdx?collection=docs"
import * as __fd_glob_94 from "../content/docs/models/zen-coder-flash.mdx?collection=docs"
import * as __fd_glob_93 from "../content/docs/models/zen-code.mdx?collection=docs"
import * as __fd_glob_92 from "../content/docs/models/zen-artist.mdx?collection=docs"
import * as __fd_glob_91 from "../content/docs/models/zen-artist-edit.mdx?collection=docs"
import * as __fd_glob_90 from "../content/docs/models/zen-agent.mdx?collection=docs"
import * as __fd_glob_89 from "../content/docs/models/zen-3d.mdx?collection=docs"
import * as __fd_glob_88 from "../content/docs/training/overview.mdx?collection=docs"
import * as __fd_glob_87 from "../content/docs/training/mlx.mdx?collection=docs"
import * as __fd_glob_86 from "../content/docs/training/cuda.mdx?collection=docs"
import * as __fd_glob_85 from "../content/docs/training/cloud.mdx?collection=docs"
import * as __fd_glob_84 from "../content/docs/getting-started/quickstart.mdx?collection=docs"
import * as __fd_glob_83 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_82 from "../content/docs/api/pricing.mdx?collection=docs"
import * as __fd_glob_81 from "../content/docs/api/models.mdx?collection=docs"
import * as __fd_glob_80 from "../content/docs/api/index.mdx?collection=docs"
import * as __fd_glob_79 from "../content/docs/api/embeddings.mdx?collection=docs"
import * as __fd_glob_78 from "../content/docs/api/chat-completions.mdx?collection=docs"
import * as __fd_glob_77 from "../content/docs/training.mdx?collection=docs"
import * as __fd_glob_76 from "../content/docs/models.mdx?collection=docs"
import * as __fd_glob_75 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_74 from "../content/docs/datasets.mdx?collection=docs"
import { default as __fd_glob_73 } from "../content/docs/meta.json?collection=docs"
import { frontmatter as __fd_glob_72 } from "../content/blog/zoo-foundation-launch.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_71 } from "../content/blog/zips-governance.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_70 } from "../content/blog/zen5-release.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_69 } from "../content/blog/zen4-ultra.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_68 } from "../content/blog/zen-reranker.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_67 } from "../content/blog/zen-mode-architecture.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_66 } from "../content/blog/zen-lm-launch.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_65 } from "../content/blog/zen-3.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_64 } from "../content/blog/training-llms-collective-intelligence.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_63 } from "../content/blog/training-gym.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_62 } from "../content/blog/qwq-max-preview.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_61 } from "../content/blog/qwq-32b.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_60 } from "../content/blog/qwq-32b-preview.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_59 } from "../content/blog/qwen3guard.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_58 } from "../content/blog/qwen3.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_57 } from "../content/blog/qwen3-embedding.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_56 } from "../content/blog/qwen3-coder.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_55 } from "../content/blog/qwen2.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_54 } from "../content/blog/qwen2.5.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_53 } from "../content/blog/qwen2.5-vl.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_52 } from "../content/blog/qwen2.5-vl-32b.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_51 } from "../content/blog/qwen2.5-turbo.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_50 } from "../content/blog/qwen2.5-omni.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_49 } from "../content/blog/qwen2.5-max.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_48 } from "../content/blog/qwen2.5-math.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_47 } from "../content/blog/qwen2.5-math-prm.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_46 } from "../content/blog/qwen2.5-llm.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_45 } from "../content/blog/qwen2.5-coder.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_44 } from "../content/blog/qwen2.5-coder-family.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_43 } from "../content/blog/qwen2.5-1m.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_42 } from "../content/blog/qwen2-vl.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_41 } from "../content/blog/qwen2-math.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_40 } from "../content/blog/qwen2-audio.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_39 } from "../content/blog/qwen1.5.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_38 } from "../content/blog/qwen1.5-32b.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_37 } from "../content/blog/qwen1.5-110b.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_36 } from "../content/blog/qwen.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_35 } from "../content/blog/qwen-vlo.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_34 } from "../content/blog/qwen-vl.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_33 } from "../content/blog/qwen-tts.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_32 } from "../content/blog/qwen-mt.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_31 } from "../content/blog/qwen-moe.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_30 } from "../content/blog/qwen-max-0428.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_29 } from "../content/blog/qwen-image.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_28 } from "../content/blog/qwen-image-edit.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_27 } from "../content/blog/qwen-agent-2405.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_26 } from "../content/blog/qvq-max-preview.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_25 } from "../content/blog/qvq-72b-preview.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_24 } from "../content/blog/proof-of-ai.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_23 } from "../content/blog/open-weights-philosophy.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_22 } from "../content/blog/ofasys.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_21 } from "../content/blog/ofa.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_20 } from "../content/blog/introducing-zen.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_19 } from "../content/blog/gt-qlora-moe-abliteration.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_18 } from "../content/blog/gspo.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_17 } from "../content/blog/grpo.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_16 } from "../content/blog/grpo-group-relative-policy-optimization.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_15 } from "../content/blog/global-load-balance.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_14 } from "../content/blog/future-of-open-ai.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_13 } from "../content/blog/federated-learning.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_12 } from "../content/blog/federated-learning-without-compromise.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_11 } from "../content/blog/experience-ledgers.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_10 } from "../content/blog/embedding-spaces-7680-dimensions.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_9 } from "../content/blog/drop-upcycling-zen-mode.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_8 } from "../content/blog/decentralized-compute.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_7 } from "../content/blog/continual-learning-sure-opcm.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_6 } from "../content/blog/codeqwen1.5.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_5 } from "../content/blog/chinese-clip.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_4 } from "../content/blog/case-for-desci.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_3 } from "../content/blog/case-for-decentralized-science.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_2 } from "../content/blog/bitdelta-behavioral-compression.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_1 } from "../content/blog/agent-nfts.mdx?collection=blog&only=frontmatter"
import { frontmatter as __fd_glob_0 } from "../content/blog/7680-dim-embeddings.mdx?collection=blog&only=frontmatter"
import { server } from '@hanzo/docs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("@hanzo/docs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const blog = await create.docLazy("blog", "content/blog", {"7680-dim-embeddings.mdx": __fd_glob_0, "agent-nfts.mdx": __fd_glob_1, "bitdelta-behavioral-compression.mdx": __fd_glob_2, "case-for-decentralized-science.mdx": __fd_glob_3, "case-for-desci.mdx": __fd_glob_4, "chinese-clip.mdx": __fd_glob_5, "codeqwen1.5.mdx": __fd_glob_6, "continual-learning-sure-opcm.mdx": __fd_glob_7, "decentralized-compute.mdx": __fd_glob_8, "drop-upcycling-zen-mode.mdx": __fd_glob_9, "embedding-spaces-7680-dimensions.mdx": __fd_glob_10, "experience-ledgers.mdx": __fd_glob_11, "federated-learning-without-compromise.mdx": __fd_glob_12, "federated-learning.mdx": __fd_glob_13, "future-of-open-ai.mdx": __fd_glob_14, "global-load-balance.mdx": __fd_glob_15, "grpo-group-relative-policy-optimization.mdx": __fd_glob_16, "grpo.mdx": __fd_glob_17, "gspo.mdx": __fd_glob_18, "gt-qlora-moe-abliteration.mdx": __fd_glob_19, "introducing-zen.mdx": __fd_glob_20, "ofa.mdx": __fd_glob_21, "ofasys.mdx": __fd_glob_22, "open-weights-philosophy.mdx": __fd_glob_23, "proof-of-ai.mdx": __fd_glob_24, "qvq-72b-preview.mdx": __fd_glob_25, "qvq-max-preview.mdx": __fd_glob_26, "qwen-agent-2405.mdx": __fd_glob_27, "qwen-image-edit.mdx": __fd_glob_28, "qwen-image.mdx": __fd_glob_29, "qwen-max-0428.mdx": __fd_glob_30, "qwen-moe.mdx": __fd_glob_31, "qwen-mt.mdx": __fd_glob_32, "qwen-tts.mdx": __fd_glob_33, "qwen-vl.mdx": __fd_glob_34, "qwen-vlo.mdx": __fd_glob_35, "qwen.mdx": __fd_glob_36, "qwen1.5-110b.mdx": __fd_glob_37, "qwen1.5-32b.mdx": __fd_glob_38, "qwen1.5.mdx": __fd_glob_39, "qwen2-audio.mdx": __fd_glob_40, "qwen2-math.mdx": __fd_glob_41, "qwen2-vl.mdx": __fd_glob_42, "qwen2.5-1m.mdx": __fd_glob_43, "qwen2.5-coder-family.mdx": __fd_glob_44, "qwen2.5-coder.mdx": __fd_glob_45, "qwen2.5-llm.mdx": __fd_glob_46, "qwen2.5-math-prm.mdx": __fd_glob_47, "qwen2.5-math.mdx": __fd_glob_48, "qwen2.5-max.mdx": __fd_glob_49, "qwen2.5-omni.mdx": __fd_glob_50, "qwen2.5-turbo.mdx": __fd_glob_51, "qwen2.5-vl-32b.mdx": __fd_glob_52, "qwen2.5-vl.mdx": __fd_glob_53, "qwen2.5.mdx": __fd_glob_54, "qwen2.mdx": __fd_glob_55, "qwen3-coder.mdx": __fd_glob_56, "qwen3-embedding.mdx": __fd_glob_57, "qwen3.mdx": __fd_glob_58, "qwen3guard.mdx": __fd_glob_59, "qwq-32b-preview.mdx": __fd_glob_60, "qwq-32b.mdx": __fd_glob_61, "qwq-max-preview.mdx": __fd_glob_62, "training-gym.mdx": __fd_glob_63, "training-llms-collective-intelligence.mdx": __fd_glob_64, "zen-3.mdx": __fd_glob_65, "zen-lm-launch.mdx": __fd_glob_66, "zen-mode-architecture.mdx": __fd_glob_67, "zen-reranker.mdx": __fd_glob_68, "zen4-ultra.mdx": __fd_glob_69, "zen5-release.mdx": __fd_glob_70, "zips-governance.mdx": __fd_glob_71, "zoo-foundation-launch.mdx": __fd_glob_72, }, {"7680-dim-embeddings.mdx": () => import("../content/blog/7680-dim-embeddings.mdx?collection=blog"), "agent-nfts.mdx": () => import("../content/blog/agent-nfts.mdx?collection=blog"), "bitdelta-behavioral-compression.mdx": () => import("../content/blog/bitdelta-behavioral-compression.mdx?collection=blog"), "case-for-decentralized-science.mdx": () => import("../content/blog/case-for-decentralized-science.mdx?collection=blog"), "case-for-desci.mdx": () => import("../content/blog/case-for-desci.mdx?collection=blog"), "chinese-clip.mdx": () => import("../content/blog/chinese-clip.mdx?collection=blog"), "codeqwen1.5.mdx": () => import("../content/blog/codeqwen1.5.mdx?collection=blog"), "continual-learning-sure-opcm.mdx": () => import("../content/blog/continual-learning-sure-opcm.mdx?collection=blog"), "decentralized-compute.mdx": () => import("../content/blog/decentralized-compute.mdx?collection=blog"), "drop-upcycling-zen-mode.mdx": () => import("../content/blog/drop-upcycling-zen-mode.mdx?collection=blog"), "embedding-spaces-7680-dimensions.mdx": () => import("../content/blog/embedding-spaces-7680-dimensions.mdx?collection=blog"), "experience-ledgers.mdx": () => import("../content/blog/experience-ledgers.mdx?collection=blog"), "federated-learning-without-compromise.mdx": () => import("../content/blog/federated-learning-without-compromise.mdx?collection=blog"), "federated-learning.mdx": () => import("../content/blog/federated-learning.mdx?collection=blog"), "future-of-open-ai.mdx": () => import("../content/blog/future-of-open-ai.mdx?collection=blog"), "global-load-balance.mdx": () => import("../content/blog/global-load-balance.mdx?collection=blog"), "grpo-group-relative-policy-optimization.mdx": () => import("../content/blog/grpo-group-relative-policy-optimization.mdx?collection=blog"), "grpo.mdx": () => import("../content/blog/grpo.mdx?collection=blog"), "gspo.mdx": () => import("../content/blog/gspo.mdx?collection=blog"), "gt-qlora-moe-abliteration.mdx": () => import("../content/blog/gt-qlora-moe-abliteration.mdx?collection=blog"), "introducing-zen.mdx": () => import("../content/blog/introducing-zen.mdx?collection=blog"), "ofa.mdx": () => import("../content/blog/ofa.mdx?collection=blog"), "ofasys.mdx": () => import("../content/blog/ofasys.mdx?collection=blog"), "open-weights-philosophy.mdx": () => import("../content/blog/open-weights-philosophy.mdx?collection=blog"), "proof-of-ai.mdx": () => import("../content/blog/proof-of-ai.mdx?collection=blog"), "qvq-72b-preview.mdx": () => import("../content/blog/qvq-72b-preview.mdx?collection=blog"), "qvq-max-preview.mdx": () => import("../content/blog/qvq-max-preview.mdx?collection=blog"), "qwen-agent-2405.mdx": () => import("../content/blog/qwen-agent-2405.mdx?collection=blog"), "qwen-image-edit.mdx": () => import("../content/blog/qwen-image-edit.mdx?collection=blog"), "qwen-image.mdx": () => import("../content/blog/qwen-image.mdx?collection=blog"), "qwen-max-0428.mdx": () => import("../content/blog/qwen-max-0428.mdx?collection=blog"), "qwen-moe.mdx": () => import("../content/blog/qwen-moe.mdx?collection=blog"), "qwen-mt.mdx": () => import("../content/blog/qwen-mt.mdx?collection=blog"), "qwen-tts.mdx": () => import("../content/blog/qwen-tts.mdx?collection=blog"), "qwen-vl.mdx": () => import("../content/blog/qwen-vl.mdx?collection=blog"), "qwen-vlo.mdx": () => import("../content/blog/qwen-vlo.mdx?collection=blog"), "qwen.mdx": () => import("../content/blog/qwen.mdx?collection=blog"), "qwen1.5-110b.mdx": () => import("../content/blog/qwen1.5-110b.mdx?collection=blog"), "qwen1.5-32b.mdx": () => import("../content/blog/qwen1.5-32b.mdx?collection=blog"), "qwen1.5.mdx": () => import("../content/blog/qwen1.5.mdx?collection=blog"), "qwen2-audio.mdx": () => import("../content/blog/qwen2-audio.mdx?collection=blog"), "qwen2-math.mdx": () => import("../content/blog/qwen2-math.mdx?collection=blog"), "qwen2-vl.mdx": () => import("../content/blog/qwen2-vl.mdx?collection=blog"), "qwen2.5-1m.mdx": () => import("../content/blog/qwen2.5-1m.mdx?collection=blog"), "qwen2.5-coder-family.mdx": () => import("../content/blog/qwen2.5-coder-family.mdx?collection=blog"), "qwen2.5-coder.mdx": () => import("../content/blog/qwen2.5-coder.mdx?collection=blog"), "qwen2.5-llm.mdx": () => import("../content/blog/qwen2.5-llm.mdx?collection=blog"), "qwen2.5-math-prm.mdx": () => import("../content/blog/qwen2.5-math-prm.mdx?collection=blog"), "qwen2.5-math.mdx": () => import("../content/blog/qwen2.5-math.mdx?collection=blog"), "qwen2.5-max.mdx": () => import("../content/blog/qwen2.5-max.mdx?collection=blog"), "qwen2.5-omni.mdx": () => import("../content/blog/qwen2.5-omni.mdx?collection=blog"), "qwen2.5-turbo.mdx": () => import("../content/blog/qwen2.5-turbo.mdx?collection=blog"), "qwen2.5-vl-32b.mdx": () => import("../content/blog/qwen2.5-vl-32b.mdx?collection=blog"), "qwen2.5-vl.mdx": () => import("../content/blog/qwen2.5-vl.mdx?collection=blog"), "qwen2.5.mdx": () => import("../content/blog/qwen2.5.mdx?collection=blog"), "qwen2.mdx": () => import("../content/blog/qwen2.mdx?collection=blog"), "qwen3-coder.mdx": () => import("../content/blog/qwen3-coder.mdx?collection=blog"), "qwen3-embedding.mdx": () => import("../content/blog/qwen3-embedding.mdx?collection=blog"), "qwen3.mdx": () => import("../content/blog/qwen3.mdx?collection=blog"), "qwen3guard.mdx": () => import("../content/blog/qwen3guard.mdx?collection=blog"), "qwq-32b-preview.mdx": () => import("../content/blog/qwq-32b-preview.mdx?collection=blog"), "qwq-32b.mdx": () => import("../content/blog/qwq-32b.mdx?collection=blog"), "qwq-max-preview.mdx": () => import("../content/blog/qwq-max-preview.mdx?collection=blog"), "training-gym.mdx": () => import("../content/blog/training-gym.mdx?collection=blog"), "training-llms-collective-intelligence.mdx": () => import("../content/blog/training-llms-collective-intelligence.mdx?collection=blog"), "zen-3.mdx": () => import("../content/blog/zen-3.mdx?collection=blog"), "zen-lm-launch.mdx": () => import("../content/blog/zen-lm-launch.mdx?collection=blog"), "zen-mode-architecture.mdx": () => import("../content/blog/zen-mode-architecture.mdx?collection=blog"), "zen-reranker.mdx": () => import("../content/blog/zen-reranker.mdx?collection=blog"), "zen4-ultra.mdx": () => import("../content/blog/zen4-ultra.mdx?collection=blog"), "zen5-release.mdx": () => import("../content/blog/zen5-release.mdx?collection=blog"), "zips-governance.mdx": () => import("../content/blog/zips-governance.mdx?collection=blog"), "zoo-foundation-launch.mdx": () => import("../content/blog/zoo-foundation-launch.mdx?collection=blog"), });

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_73, }, {"datasets.mdx": __fd_glob_74, "index.mdx": __fd_glob_75, "models.mdx": __fd_glob_76, "training.mdx": __fd_glob_77, "api/chat-completions.mdx": __fd_glob_78, "api/embeddings.mdx": __fd_glob_79, "api/index.mdx": __fd_glob_80, "api/models.mdx": __fd_glob_81, "api/pricing.mdx": __fd_glob_82, "getting-started/installation.mdx": __fd_glob_83, "getting-started/quickstart.mdx": __fd_glob_84, "training/cloud.mdx": __fd_glob_85, "training/cuda.mdx": __fd_glob_86, "training/mlx.mdx": __fd_glob_87, "training/overview.mdx": __fd_glob_88, "models/zen-3d.mdx": __fd_glob_89, "models/zen-agent.mdx": __fd_glob_90, "models/zen-artist-edit.mdx": __fd_glob_91, "models/zen-artist.mdx": __fd_glob_92, "models/zen-code.mdx": __fd_glob_93, "models/zen-coder-flash.mdx": __fd_glob_94, "models/zen-coder.mdx": __fd_glob_95, "models/zen-designer.mdx": __fd_glob_96, "models/zen-director.mdx": __fd_glob_97, "models/zen-dub-live.mdx": __fd_glob_98, "models/zen-dub.mdx": __fd_glob_99, "models/zen-eco.mdx": __fd_glob_100, "models/zen-embedding.mdx": __fd_glob_101, "models/zen-foley.mdx": __fd_glob_102, "models/zen-guard-gen.mdx": __fd_glob_103, "models/zen-guard-stream.mdx": __fd_glob_104, "models/zen-guard.mdx": __fd_glob_105, "models/zen-live.mdx": __fd_glob_106, "models/zen-max.mdx": __fd_glob_107, "models/zen-musician.mdx": __fd_glob_108, "models/zen-nano.mdx": __fd_glob_109, "models/zen-next.mdx": __fd_glob_110, "models/zen-omni.mdx": __fd_glob_111, "models/zen-pro.mdx": __fd_glob_112, "models/zen-reranker.mdx": __fd_glob_113, "models/zen-scribe.mdx": __fd_glob_114, "models/zen-translator.mdx": __fd_glob_115, "models/zen-video-i2v.mdx": __fd_glob_116, "models/zen-video.mdx": __fd_glob_117, "models/zen-vl.mdx": __fd_glob_118, "models/zen-voyager.mdx": __fd_glob_119, "models/zen-world.mdx": __fd_glob_120, "models/zen.mdx": __fd_glob_121, "models/zen3-asr-v1.mdx": __fd_glob_122, "models/zen3-asr.mdx": __fd_glob_123, "models/zen3-audio-fast.mdx": __fd_glob_124, "models/zen3-audio.mdx": __fd_glob_125, "models/zen3-embedding-medium.mdx": __fd_glob_126, "models/zen3-embedding-small.mdx": __fd_glob_127, "models/zen3-embedding.mdx": __fd_glob_128, "models/zen3-guard.mdx": __fd_glob_129, "models/zen3-image-dev.mdx": __fd_glob_130, "models/zen3-image-fast.mdx": __fd_glob_131, "models/zen3-image-jp.mdx": __fd_glob_132, "models/zen3-image-max.mdx": __fd_glob_133, "models/zen3-image-playground.mdx": __fd_glob_134, "models/zen3-image-sdxl.mdx": __fd_glob_135, "models/zen3-image-ssd.mdx": __fd_glob_136, "models/zen3-image.mdx": __fd_glob_137, "models/zen3-nano.mdx": __fd_glob_138, "models/zen3-omni.mdx": __fd_glob_139, "models/zen3-reranker-medium.mdx": __fd_glob_140, "models/zen3-reranker-small.mdx": __fd_glob_141, "models/zen3-reranker.mdx": __fd_glob_142, "models/zen3-tts-fast.mdx": __fd_glob_143, "models/zen3-tts-hd.mdx": __fd_glob_144, "models/zen3-tts.mdx": __fd_glob_145, "models/zen3-vl.mdx": __fd_glob_146, "models/zen4-coder-flash.mdx": __fd_glob_147, "models/zen4-coder-pro.mdx": __fd_glob_148, "models/zen4-coder.mdx": __fd_glob_149, "models/zen4-max.mdx": __fd_glob_150, "models/zen4-mini.mdx": __fd_glob_151, "models/zen4-pro.mdx": __fd_glob_152, "models/zen4-thinking.mdx": __fd_glob_153, "models/zen4-ultra.mdx": __fd_glob_154, "models/zen4.1.mdx": __fd_glob_155, "models/zen4.mdx": __fd_glob_156, "models/zen5-coder.mdx": __fd_glob_157, "models/zen5-max.mdx": __fd_glob_158, "models/zen5-mini.mdx": __fd_glob_159, "models/zen5-pro.mdx": __fd_glob_160, "models/zen5-ultra.mdx": __fd_glob_161, "models/zen5.mdx": __fd_glob_162, });