export interface Paper {
  slug: string;
  title: string;
  description: string;
  topics: string[];
  pdf: string;
  source: string;
}

export interface Organization {
  id: string;
  name: string;
  fullName: string;
  description: string;
  repo: string;
  color: string;
  papers: Paper[];
}

function ghPdf(org: string, repo: string, name: string) {
  return `https://github.com/${org}/${repo}/raw/main/pdfs/${name}.pdf`;
}

function ghTex(org: string, repo: string, name: string) {
  return `https://github.com/${org}/${repo}/blob/main/${name}.tex`;
}

export const organizations: Organization[] = [
  {
    id: 'hanzo',
    name: 'Hanzo AI',
    fullName: 'Hanzo AI Inc',
    description: 'AI infrastructure, commerce platform, and agent systems',
    repo: 'hanzoai/papers',
    color: '#fff',
    papers: [
      {
        slug: 'hanzo-aso',
        title: 'ASO: Training-Free Group-Relative Policy Optimization for Agentic Code Generation',
        description: 'Active Semantic Optimization achieving 99.8% cost reduction ($18 vs $10,000+) via semantic optimization with Hamiltonian invariant.',
        topics: ['ASO', 'GRPO', 'Code Generation', 'Cost Reduction'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-aso'),
        source: ghTex('hanzoai', 'papers', 'hanzo-aso'),
      },
      {
        slug: 'hanzo-dso',
        title: 'DSO: Decentralized Semantic Optimization with Byzantine-Robust Prior Aggregation',
        description: 'Decentralized learning protocol with Byzantine fault tolerance and three-layer semantic storage architecture.',
        topics: ['DSO', 'Byzantine Robust', 'Decentralized Learning'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-dso'),
        source: ghTex('hanzoai', 'papers', 'hanzo-dso'),
      },
      {
        slug: 'hanzo-hmm',
        title: 'HMM: Hamiltonian Market Maker for Decentralized AI Compute Exchange',
        description: 'Physics-inspired market maker using Hamiltonian dynamics for optimal pricing and minimal slippage in AI compute markets.',
        topics: ['HMM', 'Market Maker', 'AI Compute', 'DeFi'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-hmm'),
        source: ghTex('hanzoai', 'papers', 'hanzo-hmm'),
      },
      {
        slug: 'hanzo-network-whitepaper',
        title: 'Hanzo Network: Hamiltonian Market Maker L1 for Decentralized AI Compute',
        description: 'Layer-1 blockchain designed for AI compute settlement with physics-inspired consensus and semantic learning.',
        topics: ['L1', 'AI Compute', 'Network Architecture'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-network-whitepaper'),
        source: ghTex('hanzoai', 'papers', 'hanzo-network-whitepaper'),
      },
      {
        slug: 'hanzo-network-architecture',
        title: 'Hanzo Network Architecture: Decentralized AI Compute with Post-Quantum Security',
        description: 'Network architecture with post-quantum cryptography and physics-inspired LLM routing.',
        topics: ['Architecture', 'Post-Quantum', 'LLM Routing'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-network-architecture'),
        source: ghTex('hanzoai', 'papers', 'hanzo-network-architecture'),
      },
      {
        slug: 'hanzo-jin-architecture',
        title: 'Jin: Unified Multimodal AI Architecture',
        description: 'Vision-language, audio, and cross-modal understanding in a unified architecture.',
        topics: ['Multimodal', 'Vision-Language', 'Audio', 'Architecture'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-jin-architecture'),
        source: ghTex('hanzoai', 'papers', 'hanzo-jin-architecture'),
      },
      {
        slug: 'hanzo-mcp-server',
        title: 'Model Context Protocol Server Architecture',
        description: 'Context management and tool execution for AI systems via the Model Context Protocol.',
        topics: ['MCP', 'Context Management', 'Tool Use'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-mcp-server'),
        source: ghTex('hanzoai', 'papers', 'hanzo-mcp-server'),
      },
      {
        slug: 'hanzo-agent-sdk',
        title: 'Hanzo Agent SDK: Orchestration, Tool Use, and Memory Systems',
        description: 'Building AI agents with multi-agent coordination, tool use, planning, and persistent memory.',
        topics: ['Agents', 'SDK', 'Tool Use', 'Memory'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-agent-sdk'),
        source: ghTex('hanzoai', 'papers', 'hanzo-agent-sdk'),
      },
      {
        slug: 'hanzo-ml-framework',
        title: 'Hanzo ML: Production ML Framework for Model Serving and A/B Testing',
        description: 'Enterprise ML operations with model versioning, feature stores, and inference infrastructure.',
        topics: ['MLOps', 'Model Serving', 'A/B Testing'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-ml-framework'),
        source: ghTex('hanzoai', 'papers', 'hanzo-ml-framework'),
      },
      {
        slug: 'hanzo-identity-nft',
        title: 'Identity NFTs for AI Agents: Capability Tokens',
        description: 'Token standard for autonomous AI agents with economic agency and identity.',
        topics: ['NFT', 'AI Identity', 'Capability Tokens'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-identity-nft'),
        source: ghTex('hanzoai', 'papers', 'hanzo-identity-nft'),
      },
      {
        slug: 'hanzo-api-gateway',
        title: 'Hanzo API Gateway: Unified Commerce API Architecture',
        description: 'API gateway architecture for unified commerce operations and integrations.',
        topics: ['API', 'Gateway', 'Commerce'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-api-gateway'),
        source: ghTex('hanzoai', 'papers', 'hanzo-api-gateway'),
      },
      {
        slug: 'hanzo-ai-commerce',
        title: 'Hanzo: An AI-First Commerce Platform',
        description: 'AI-native commerce platform architecture and capabilities.',
        topics: ['Commerce', 'AI Platform', 'E-Commerce'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-ai-commerce'),
        source: ghTex('hanzoai', 'papers', 'hanzo-ai-commerce'),
      },
      {
        slug: 'hanzo-analytics-ml',
        title: 'Machine Learning for Commerce Analytics',
        description: 'Predictive models for customer behavior using machine learning.',
        topics: ['Analytics', 'ML', 'Predictions'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-analytics-ml'),
        source: ghTex('hanzoai', 'papers', 'hanzo-analytics-ml'),
      },
      {
        slug: 'hanzo-checkout',
        title: 'Hanzo Checkout: Frictionless Payment Processing',
        description: 'Modern payment processing architecture for e-commerce.',
        topics: ['Payments', 'Checkout', 'Commerce'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-checkout'),
        source: ghTex('hanzoai', 'papers', 'hanzo-checkout'),
      },
      {
        slug: 'hanzo-sdk-ecosystem',
        title: 'The Hanzo SDK Ecosystem: Multi-Language Commerce Integration',
        description: 'TypeScript, Python, Go, and Rust SDK architecture for commerce.',
        topics: ['SDK', 'Multi-Language', 'Integration'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-sdk-ecosystem'),
        source: ghTex('hanzoai', 'papers', 'hanzo-sdk-ecosystem'),
      },
      {
        slug: 'hanzo-webhooks',
        title: 'Event-Driven Commerce: Webhook Architecture',
        description: 'Real-time webhook architecture for event-driven commerce integration.',
        topics: ['Webhooks', 'Events', 'Real-Time'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-webhooks'),
        source: ghTex('hanzoai', 'papers', 'hanzo-webhooks'),
      },
      {
        slug: 'astle-reactive-sdk',
        title: 'Astle.js: A Reactive JavaScript SDK for Commerce',
        description: 'Reactive JavaScript SDK architecture for commerce applications.',
        topics: ['JavaScript', 'SDK', 'Reactive'],
        pdf: ghPdf('hanzoai', 'papers', 'astle-reactive-sdk'),
        source: ghTex('hanzoai', 'papers', 'astle-reactive-sdk'),
      },
      {
        slug: 'crowdstart-commerce',
        title: 'Crowdstart: A Cloud-Native E-Commerce Platform',
        description: 'Cloud-native e-commerce platform design and architecture.',
        topics: ['Cloud-Native', 'E-Commerce', 'Platform'],
        pdf: ghPdf('hanzoai', 'papers', 'crowdstart-commerce'),
        source: ghTex('hanzoai', 'papers', 'crowdstart-commerce'),
      },
      {
        slug: 'earle-genetic-marketing',
        title: 'Earle: Genetic Algorithms for Automated Marketing Optimization',
        description: 'Evolutionary algorithms applied to marketing campaign optimization.',
        topics: ['Genetic Algorithms', 'Marketing', 'Optimization'],
        pdf: ghPdf('hanzoai', 'papers', 'earle-genetic-marketing'),
        source: ghTex('hanzoai', 'papers', 'earle-genetic-marketing'),
      },
      {
        slug: 'verus-analytics',
        title: 'Verus: Real-Time Commerce Analytics at Scale',
        description: 'Real-time analytics infrastructure for commerce at scale.',
        topics: ['Analytics', 'Real-Time', 'Scale'],
        pdf: ghPdf('hanzoai', 'papers', 'verus-analytics'),
        source: ghTex('hanzoai', 'papers', 'verus-analytics'),
      },
      {
        slug: 'hanzo-jin',
        title: 'Jin: Unified Multimodal Architecture (Extended)',
        description: 'Extended technical report on the Jin multimodal AI architecture.',
        topics: ['Multimodal', 'Architecture', 'Technical Report'],
        pdf: ghPdf('hanzoai', 'papers', 'hanzo-jin'),
        source: ghTex('hanzoai', 'papers', 'hanzo-jin'),
      },
    ],
  },
  {
    id: 'lux',
    name: 'Lux Network',
    fullName: 'Lux Network',
    description: 'Post-quantum secure blockchain infrastructure for AI compute settlement',
    repo: 'luxfi/papers',
    color: '#f59e0b',
    papers: [
      {
        slug: 'lux-consensus',
        title: 'Lux Consensus: Physics-Inspired Metastable Blockchain Consensus',
        description: 'Novel consensus mechanism using physics-inspired metastable dynamics.',
        topics: ['Consensus', 'Physics-Inspired', 'Metastable'],
        pdf: ghPdf('luxfi', 'papers', 'lux-consensus'),
        source: ghTex('luxfi', 'papers', 'lux-consensus'),
      },
      {
        slug: 'lux-quantum-consensus',
        title: 'Lux Quantum Consensus: Post-Quantum Secure Multi-Consensus',
        description: 'Multi-consensus architecture with post-quantum cryptographic security.',
        topics: ['Post-Quantum', 'Multi-Consensus', 'Security'],
        pdf: ghPdf('luxfi', 'papers', 'lux-quantum-consensus'),
        source: ghTex('luxfi', 'papers', 'lux-quantum-consensus'),
      },
      {
        slug: 'lux-quasar-consensus',
        title: 'Quasar: Quantum-Secure Multi-Engine Consensus with Dual-Certificate Finality',
        description: 'Multi-engine consensus with quantum-safe dual-certificate finality.',
        topics: ['Quasar', 'Quantum-Safe', 'Dual-Certificate'],
        pdf: ghPdf('luxfi', 'papers', 'lux-quasar-consensus'),
        source: ghTex('luxfi', 'papers', 'lux-quasar-consensus'),
      },
      {
        slug: 'lux-fpc-consensus',
        title: 'Fast Probabilistic Consensus: Adaptive Threshold with Phase-Shift Dynamics',
        description: 'Adaptive threshold consensus using phase-shift dynamics for fast finality.',
        topics: ['FPC', 'Adaptive Threshold', 'Fast Finality'],
        pdf: ghPdf('luxfi', 'papers', 'lux-fpc-consensus'),
        source: ghTex('luxfi', 'papers', 'lux-fpc-consensus'),
      },
      {
        slug: 'lux-ethfalcon-post-quantum',
        title: 'ETHFALCON: EVM-Optimized Post-Quantum Signatures',
        description: 'Practical lattice-based cryptography optimized for the EVM.',
        topics: ['ETHFALCON', 'PQC', 'EVM', 'Lattice'],
        pdf: ghPdf('luxfi', 'papers', 'lux-ethfalcon-post-quantum'),
        source: ghTex('luxfi', 'papers', 'lux-ethfalcon-post-quantum'),
      },
      {
        slug: 'lux-ntt-transform',
        title: 'NTT Transform: Post-Quantum Cryptography on EVM with 85% Gas Reduction',
        description: 'Number Theoretic Transform enabling efficient PQC on Ethereum.',
        topics: ['NTT', 'PQC', 'Gas Optimization'],
        pdf: ghPdf('luxfi', 'papers', 'lux-ntt-transform'),
        source: ghTex('luxfi', 'papers', 'lux-ntt-transform'),
      },
      {
        slug: 'lux-universal-threshold-signatures',
        title: 'Universal Threshold Signatures: Multi-Chain Cryptographic Infrastructure',
        description: 'Threshold signature infrastructure with post-quantum security across chains.',
        topics: ['Threshold Signatures', 'Multi-Chain', 'PQC'],
        pdf: ghPdf('luxfi', 'papers', 'lux-universal-threshold-signatures'),
        source: ghTex('luxfi', 'papers', 'lux-universal-threshold-signatures'),
      },
      {
        slug: 'lux-bridge',
        title: 'Lux Bridge: Zero-Knowledge Cross-Chain Communication',
        description: 'ZK-based cross-chain bridge with sub-second finality.',
        topics: ['Bridge', 'Zero-Knowledge', 'Cross-Chain'],
        pdf: ghPdf('luxfi', 'papers', 'lux-bridge'),
        source: ghTex('luxfi', 'papers', 'lux-bridge'),
      },
      {
        slug: 'lux-zchain',
        title: 'Z-Chain: Privacy-Preserving Smart Contracts with Zero-Knowledge Proofs',
        description: 'Privacy-first smart contract execution with ZK proofs.',
        topics: ['Z-Chain', 'Privacy', 'ZK Proofs'],
        pdf: ghPdf('luxfi', 'papers', 'lux-zchain'),
        source: ghTex('luxfi', 'papers', 'lux-zchain'),
      },
      {
        slug: 'lux-verkle-trees',
        title: 'Verkle Trees: Constant-Size Proofs for Stateless Clients',
        description: 'Verkle tree implementation for stateless blockchain clients.',
        topics: ['Verkle Trees', 'Stateless Clients', 'Proofs'],
        pdf: ghPdf('luxfi', 'papers', 'lux-verkle-trees'),
        source: ghTex('luxfi', 'papers', 'lux-verkle-trees'),
      },
      {
        slug: 'lux-fraud-proofs',
        title: 'Fraud Proofs: Optimistic Rollup Security on Lux',
        description: 'Interactive fraud proof verification for optimistic rollups.',
        topics: ['Fraud Proofs', 'Rollups', 'Security'],
        pdf: ghPdf('luxfi', 'papers', 'lux-fraud-proofs'),
        source: ghTex('luxfi', 'papers', 'lux-fraud-proofs'),
      },
      {
        slug: 'lux-achain-attestation',
        title: 'A-Chain: Unified TEE Attestation for Decentralized AI Compute',
        description: 'Trusted execution environment attestation for AI compute verification.',
        topics: ['TEE', 'Attestation', 'AI Compute'],
        pdf: ghPdf('luxfi', 'papers', 'lux-achain-attestation'),
        source: ghTex('luxfi', 'papers', 'lux-achain-attestation'),
      },
      {
        slug: 'lux-tee-computing-mesh',
        title: 'Lux TEE Mesh: Decentralized Confidential Computing Infrastructure',
        description: 'Confidential computing mesh for blockchain networks.',
        topics: ['TEE', 'Confidential Computing', 'Mesh'],
        pdf: ghPdf('luxfi', 'papers', 'lux-tee-computing-mesh'),
        source: ghTex('luxfi', 'papers', 'lux-tee-computing-mesh'),
      },
      {
        slug: 'lux-mchain-mpc',
        title: 'M-Chain: Decentralized MPC Custody with Quantum-Safe Threshold Signatures',
        description: 'Multi-party computation custody with quantum-safe key management.',
        topics: ['MPC', 'Custody', 'Quantum-Safe'],
        pdf: ghPdf('luxfi', 'papers', 'lux-mchain-mpc'),
        source: ghTex('luxfi', 'papers', 'lux-mchain-mpc'),
      },
      {
        slug: 'lux-gchain-graphql',
        title: 'G-Chain: Unified GraphQL Engine with Decentralized Indexing',
        description: 'GraphQL query engine for decentralized multi-chain state.',
        topics: ['GraphQL', 'Indexing', 'Multi-Chain'],
        pdf: ghPdf('luxfi', 'papers', 'lux-gchain-graphql'),
        source: ghTex('luxfi', 'papers', 'lux-gchain-graphql'),
      },
      {
        slug: 'lux-id-did-specification',
        title: 'Lux ID: Decentralized Identity and Universal Access Management',
        description: 'Five-year journey from Web2 to Web3 identity.',
        topics: ['DID', 'Identity', 'Web3'],
        pdf: ghPdf('luxfi', 'papers', 'lux-id-did-specification'),
        source: ghTex('luxfi', 'papers', 'lux-id-did-specification'),
      },
      {
        slug: 'lux-id-iam',
        title: 'Lux.id: Decentralized Identity and Access Management',
        description: 'IAM for Web3 with decentralized identity.',
        topics: ['IAM', 'DID', 'Access Management'],
        pdf: ghPdf('luxfi', 'papers', 'lux-id-iam'),
        source: ghTex('luxfi', 'papers', 'lux-id-iam'),
      },
      {
        slug: 'lux-governance-dao',
        title: 'Lux Governance: Unified DAO Framework',
        description: 'DAO framework for multi-ecosystem coordination.',
        topics: ['DAO', 'Governance', 'Multi-Ecosystem'],
        pdf: ghPdf('luxfi', 'papers', 'lux-governance-dao'),
        source: ghTex('luxfi', 'papers', 'lux-governance-dao'),
      },
      {
        slug: 'lux-dao-governance-framework',
        title: 'Lux DAO: Modular Governance Framework for Decentralized Organizations',
        description: 'Modular governance with flexible voting and execution mechanisms.',
        topics: ['DAO', 'Modular Governance', 'Voting'],
        pdf: ghPdf('luxfi', 'papers', 'lux-dao-governance-framework'),
        source: ghTex('luxfi', 'papers', 'lux-dao-governance-framework'),
      },
      {
        slug: 'lux-lightspeed-dex',
        title: 'Lux Lightspeed DEX: High-Frequency Trading',
        description: 'High-frequency decentralized exchange architecture.',
        topics: ['DEX', 'HFT', 'Trading'],
        pdf: ghPdf('luxfi', 'papers', 'lux-lightspeed-dex'),
        source: ghTex('luxfi', 'papers', 'lux-lightspeed-dex'),
      },
      {
        slug: 'lux-perpetuals-derivatives',
        title: 'Lux Perpetuals: High-Leverage Derivatives',
        description: 'Perpetual futures with automated risk management.',
        topics: ['Perpetuals', 'Derivatives', 'Risk Management'],
        pdf: ghPdf('luxfi', 'papers', 'lux-perpetuals-derivatives'),
        source: ghTex('luxfi', 'papers', 'lux-perpetuals-derivatives'),
      },
      {
        slug: 'lux-credit-lending',
        title: 'Lux Credit: Zero-Interest Self-Repaying Lending Protocol',
        description: 'Self-repaying lending with 90% LTV and cross-chain collateral.',
        topics: ['Lending', 'DeFi', 'Cross-Chain'],
        pdf: ghPdf('luxfi', 'papers', 'lux-credit-lending'),
        source: ghTex('luxfi', 'papers', 'lux-credit-lending'),
      },
      {
        slug: 'lux-market-nft',
        title: 'Lux.market: Aggregated NFT Marketplace with Instant Liquidity',
        description: 'NFT marketplace aggregation with instant liquidity protocols.',
        topics: ['NFT', 'Marketplace', 'Liquidity'],
        pdf: ghPdf('luxfi', 'papers', 'lux-market-nft'),
        source: ghTex('luxfi', 'papers', 'lux-market-nft'),
      },
      {
        slug: 'lux-oracle-infrastructure',
        title: 'Lux Oracle: Decentralized Price Feeds and AI-Powered Data Oracles',
        description: 'Oracle infrastructure with AI-powered data feeds.',
        topics: ['Oracle', 'Price Feeds', 'AI-Powered'],
        pdf: ghPdf('luxfi', 'papers', 'lux-oracle-infrastructure'),
        source: ghTex('luxfi', 'papers', 'lux-oracle-infrastructure'),
      },
    ],
  },
  {
    id: 'zoo',
    name: 'Zoo Labs',
    fullName: 'Zoo Labs Foundation',
    description: 'Open AI research network and decentralized science (DeSci)',
    repo: 'zooai/papers',
    color: '#8b5cf6',
    papers: [
      {
        slug: 'zoo-foundation-mission',
        title: 'Zoo Labs Foundation: AI-Blockchain Research for Conservation, Education, and Science',
        description: '501(c)(3) non-profit mission: Conservation AI, Educational AI, and Frontier AI research.',
        topics: ['Foundation', 'Conservation', 'Education', 'Mission'],
        pdf: ghPdf('zooai', 'papers', 'zoo-foundation-mission'),
        source: ghTex('zooai', 'papers', 'zoo-foundation-mission'),
      },
      {
        slug: 'zoo-network-architecture',
        title: 'Zoo Network: Decentralized AI Training and Inference Layer',
        description: 'L2 AI specialization layer with HLLM integration and federated learning.',
        topics: ['Architecture', 'L2', 'Federated Learning'],
        pdf: ghPdf('zooai', 'papers', 'zoo-network-architecture'),
        source: ghTex('zooai', 'papers', 'zoo-network-architecture'),
      },
      {
        slug: 'zoo-tokenomics',
        title: 'Zoo Tokenomics: 100% Airdrop Community-Owned AI Infrastructure',
        description: '100% airdrop tokenomics with zero VC/private sales and democratic validator participation.',
        topics: ['Tokenomics', 'Airdrop', 'DAO Governance'],
        pdf: ghPdf('zooai', 'papers', 'zoo-tokenomics'),
        source: ghTex('zooai', 'papers', 'zoo-tokenomics'),
      },
      {
        slug: 'gym-training-platform',
        title: 'Gym: Democratizing AI Model Training Through Open-Source Infrastructure',
        description: 'Comprehensive open-source platform supporting 100+ models and 8 training methods.',
        topics: ['Gym', 'Training', 'Open Source'],
        pdf: ghPdf('zooai', 'papers', 'gym-training-platform'),
        source: ghTex('zooai', 'papers', 'gym-training-platform'),
      },
      {
        slug: 'hllm-training-free-grpo',
        title: 'HLLM: Hamiltonian LLMs with Training-Free GRPO',
        description: '99.8% cost reduction ($18 vs $10,000+) and +2.7% accuracy via semantic optimization.',
        topics: ['HLLM', 'GRPO', 'Cost Reduction', 'Optimization'],
        pdf: ghPdf('zooai', 'papers', 'hllm-training-free-grpo'),
        source: ghTex('zooai', 'papers', 'hllm-training-free-grpo'),
      },
      {
        slug: 'experience-ledger-dso',
        title: 'Experience Ledger: Decentralized Semantic Optimization for LLMs',
        description: 'DSO with Byzantine-robust curation, three-layer storage, and 7680-dim embeddings.',
        topics: ['DSO', 'Experience Ledger', 'Byzantine Robust'],
        pdf: ghPdf('zooai', 'papers', 'experience-ledger-dso'),
        source: ghTex('zooai', 'papers', 'experience-ledger-dso'),
      },
      {
        slug: 'zip-002-zen-reranker',
        title: 'ZIP-002: Zen-Reranker Integration for Decentralized Semantic Optimization',
        description: 'Native 7680-dimensional embeddings with BitDelta compression (31.87x ratio).',
        topics: ['ZIP-002', 'Zen-Reranker', 'Embeddings'],
        pdf: ghPdf('zooai', 'papers', 'zip-002-zen-reranker'),
        source: ghTex('zooai', 'papers', 'zip-002-zen-reranker'),
      },
      {
        slug: 'zoo-dso',
        title: 'Zoo DSO: Decentralized Semantic Optimization with Byzantine-Robust Aggregation',
        description: 'Decentralized semantic optimization protocol for the Zoo network.',
        topics: ['DSO', 'Byzantine Robust', 'Decentralized'],
        pdf: ghPdf('zooai', 'papers', 'zoo-dso'),
        source: ghTex('zooai', 'papers', 'zoo-dso'),
      },
      {
        slug: 'zoo-experience-ledger',
        title: 'Zoo Experience Ledger: Content-Addressable Semantic Memory',
        description: 'Content-addressable semantic memory system for decentralized AI.',
        topics: ['Experience Ledger', 'Semantic Memory', 'Content-Addressable'],
        pdf: ghPdf('zooai', 'papers', 'zoo-experience-ledger'),
        source: ghTex('zooai', 'papers', 'zoo-experience-ledger'),
      },
      {
        slug: 'zoo-poai-consensus',
        title: 'Proof of AI: Consensus for Verifiable Compute Contribution',
        description: 'Consensus mechanism for verifying and rewarding AI compute contributions.',
        topics: ['PoAI', 'Consensus', 'Verifiable Compute'],
        pdf: ghPdf('zooai', 'papers', 'zoo-poai-consensus'),
        source: ghTex('zooai', 'papers', 'zoo-poai-consensus'),
      },
      {
        slug: 'poai-consensus',
        title: 'Proof of AI: Consensus Mechanisms for ML Workloads',
        description: 'Consensus mechanisms designed for machine learning workloads.',
        topics: ['PoAI', 'ML Consensus', 'Proof Systems'],
        pdf: ghPdf('zooai', 'papers', 'poai-consensus'),
        source: ghTex('zooai', 'papers', 'poai-consensus'),
      },
      {
        slug: 'zoo-agent-nft',
        title: 'Agent NFTs: Token Standard for Autonomous AI Agents',
        description: 'Token standard for AI agents with economic agency.',
        topics: ['Agent NFT', 'Token Standard', 'AI Agents'],
        pdf: ghPdf('zooai', 'papers', 'zoo-agent-nft'),
        source: ghTex('zooai', 'papers', 'zoo-agent-nft'),
      },
      {
        slug: 'agent-nft',
        title: 'Agent NFTs: Tokenized AI Ownership and Governance',
        description: 'Governance and ownership framework for tokenized AI agents.',
        topics: ['NFT', 'AI Ownership', 'Governance'],
        pdf: ghPdf('zooai', 'papers', 'agent-nft'),
        source: ghTex('zooai', 'papers', 'agent-nft'),
      },
      {
        slug: 'experience-ledger',
        title: 'Experience Ledgers: Learning from Human-AI Interaction',
        description: 'Persistent semantic memory from human-AI interaction.',
        topics: ['Experience Ledger', 'Human-AI', 'Semantic Memory'],
        pdf: ghPdf('zooai', 'papers', 'experience-ledger'),
        source: ghTex('zooai', 'papers', 'experience-ledger'),
      },
      {
        slug: 'federated-dso',
        title: 'Federated DSO: Privacy-Preserving Distributed Learning for LLMs',
        description: 'Privacy-preserving distributed learning using federated DSO.',
        topics: ['Federated', 'Privacy', 'Distributed Learning'],
        pdf: ghPdf('zooai', 'papers', 'federated-dso'),
        source: ghTex('zooai', 'papers', 'federated-dso'),
      },
      {
        slug: 'embedding-7680',
        title: 'High-Dimensional Embedding Spaces for Semantic Search',
        description: 'The case for 7680-dimensional embedding spaces in semantic search.',
        topics: ['Embeddings', '7680-Dim', 'Semantic Search'],
        pdf: ghPdf('zooai', 'papers', 'embedding-7680'),
        source: ghTex('zooai', 'papers', 'embedding-7680'),
      },
    ],
  },
  {
    id: 'zen',
    name: 'Zen LM',
    fullName: 'Zen LM',
    description: 'Frontier AI models from 600M to 1T+ parameters',
    repo: 'zenlm/papers',
    color: '#06b6d4',
    papers: [
      {
        slug: 'zen_family_overview',
        title: 'The Zen AI Model Family: Democratizing AI Through Efficient Architecture',
        description: 'Technical overview of the full Zen model family and architecture whitepaper.',
        topics: ['Overview', 'Architecture', 'Model Family'],
        pdf: ghPdf('zenlm', 'papers', 'zen_family_overview'),
        source: ghTex('zenlm', 'papers', 'zen_family_overview'),
      },
      {
        slug: 'zen-coder_whitepaper',
        title: 'Zen Coder: Agentic Code Generation Models (4B-1T)',
        description: 'Code generation models with agentic capabilities across parameter scales.',
        topics: ['Coder', 'Code Generation', 'Agentic'],
        pdf: ghPdf('zenlm', 'papers', 'zen-coder_whitepaper'),
        source: ghTex('zenlm', 'papers', 'zen-coder_whitepaper'),
      },
      {
        slug: 'zen-omni_whitepaper',
        title: 'Zen-Omni: Multimodal Text Model',
        description: 'Multimodal text understanding and generation.',
        topics: ['Omni', 'Multimodal', 'Text'],
        pdf: ghPdf('zenlm', 'papers', 'zen-omni_whitepaper'),
        source: ghTex('zenlm', 'papers', 'zen-omni_whitepaper'),
      },
      {
        slug: 'zen-next_whitepaper',
        title: 'Zen-Next: Flagship Model',
        description: 'Next-generation flagship model technical report.',
        topics: ['Flagship', 'Next-Gen', 'Model'],
        pdf: ghPdf('zenlm', 'papers', 'zen-next_whitepaper'),
        source: ghTex('zenlm', 'papers', 'zen-next_whitepaper'),
      },
      {
        slug: 'zen-nano_whitepaper',
        title: 'Zen-Nano: Mobile and IoT Intelligence',
        description: 'Ultra-efficient models for mobile and IoT deployment.',
        topics: ['Nano', 'Mobile', 'IoT', 'Edge'],
        pdf: ghPdf('zenlm', 'papers', 'zen-nano_whitepaper'),
        source: ghTex('zenlm', 'papers', 'zen-nano_whitepaper'),
      },
      {
        slug: 'zen-eco_whitepaper',
        title: 'Zen-Eco: Consumer Hardware Models',
        description: 'Models optimized for consumer-grade hardware.',
        topics: ['Eco', 'Consumer', 'Efficient'],
        pdf: ghPdf('zenlm', 'papers', 'zen-eco_whitepaper'),
        source: ghTex('zenlm', 'papers', 'zen-eco_whitepaper'),
      },
      {
        slug: 'zen-artist_whitepaper',
        title: 'Zen-Artist: Text-to-Image Generation',
        description: 'Text-to-image generation model technical whitepaper.',
        topics: ['Artist', 'Text-to-Image', 'Generation'],
        pdf: ghPdf('zenlm', 'papers', 'zen-artist_whitepaper'),
        source: ghTex('zenlm', 'papers', 'zen-artist_whitepaper'),
      },
      {
        slug: 'zen-artist-edit_whitepaper',
        title: 'Zen-Artist-Edit: Image Editing and Inpainting',
        description: 'Image editing and inpainting capabilities.',
        topics: ['Artist', 'Image Editing', 'Inpainting'],
        pdf: ghPdf('zenlm', 'papers', 'zen-artist-edit_whitepaper'),
        source: ghTex('zenlm', 'papers', 'zen-artist-edit_whitepaper'),
      },
      {
        slug: 'zen-designer-instruct_whitepaper',
        title: 'Zen-Designer-Instruct: Design Generation',
        description: 'Instruction-following design generation model.',
        topics: ['Designer', 'Instruct', 'Design'],
        pdf: ghPdf('zenlm', 'papers', 'zen-designer-instruct_whitepaper'),
        source: ghTex('zenlm', 'papers', 'zen-designer-instruct_whitepaper'),
      },
      {
        slug: 'zen-designer-thinking_whitepaper',
        title: 'Zen-Designer-Thinking: Visual Reasoning and Analysis',
        description: 'Visual reasoning and analysis for design tasks.',
        topics: ['Designer', 'Visual Reasoning', 'Analysis'],
        pdf: ghPdf('zenlm', 'papers', 'zen-designer-thinking_whitepaper'),
        source: ghTex('zenlm', 'papers', 'zen-designer-thinking_whitepaper'),
      },
      {
        slug: 'zen-scribe_whitepaper',
        title: 'Zen-Scribe: Speech Recognition and Transcription',
        description: 'Speech recognition and transcription model.',
        topics: ['Scribe', 'Speech', 'Transcription'],
        pdf: ghPdf('zenlm', 'papers', 'zen-scribe_whitepaper'),
        source: ghTex('zenlm', 'papers', 'zen-scribe_whitepaper'),
      },
      {
        slug: 'zen-guard_whitepaper',
        title: 'Zen-Guard: Multilingual Safety Moderation for AI Systems',
        description: 'Safety and content moderation across languages.',
        topics: ['Guard', 'Safety', 'Moderation', 'Multilingual'],
        pdf: ghPdf('zenlm', 'papers', 'zen-guard_whitepaper'),
        source: ghTex('zenlm', 'papers', 'zen-guard_whitepaper'),
      },
      {
        slug: 'zen-reranker',
        title: 'Zen-Reranker: Native 7680-Dimensional Embeddings for Semantic Optimization',
        description: 'High-dimensional embeddings with BitDelta compression for semantic search.',
        topics: ['Reranker', 'Embeddings', '7680-Dim'],
        pdf: ghPdf('zenlm', 'papers', 'zen-reranker'),
        source: ghTex('zenlm', 'papers', 'zen-reranker'),
      },
    ],
  },
];

export function getAllPapers(): (Paper & { org: Organization })[] {
  return organizations.flatMap((org) =>
    org.papers.map((paper) => ({ ...paper, org })),
  );
}

export function getOrganization(id: string): Organization | undefined {
  return organizations.find((org) => org.id === id);
}
